#Creating EBS Dyanmic Volume fo MySQL using K8 code

apiVersion: v1
kind: Service   #headless service
metadata:
  name: mysql-headless
  namespace: expense
spec:
  clusterIP: None
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: v1
kind: Service   #noraml service
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    project: expense
    component: mysql
    tier: db
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
#ADd statefulset code

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: expense
spec:
  selector:
    matchLabels:
      project: expense
      component: mysql
      tier: db # has to match .spec.template.metadata.labels
  serviceName: "mysql-headless"
  replicas: 2 # by default is 1
  template:
    metadata:
      labels:
        project: expense
        component: mysql
        tier: db # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: kdprasad028/mysql:v1
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "sc-dynamic-ebs"
      resources:
        requests:
          storage: 1Gi